# Generated by Django 5.2 on 2026-04-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_plugin', '0003_remove_order_is_urgent_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
