# Generated by Django 5.2 on 2026-04-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_plugin', '0004_order_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
