# Generated by Django 5.2 on 2026-04-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('1st', '1st Grade'), ('2nd', '2nd Grade'), ('3rd', '3rd Grade')], max_length=10, null=True),
        ),
    ]
