# Generated by Django 5.2 on 2026-04-28 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_plugin', '0002_alter_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and spaces only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\s.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers, spaces, and @/./+/-/_ characters.')]),
        ),
    ]
