# Generated by Django 5.2 on 2026-04-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_plugin', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
