# Generated by Django 5.2 on 2026-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_plugin', '0004_user_ban_until_user_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_transaction_threshold', models.IntegerField(default=7)),
                ('premium_spending_threshold', models.DecimalField(decimal_places=2, default=3000000.0, max_digits=12)),
                ('premium_discount_percentage', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
            ],
        ),
    ]
