# Generated by Django 5.2 on 2026-04-28 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.FloatField(default=1.0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_plugin.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_plugin.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(through='inventory_plugin.ProductMaterial', to='inventory_plugin.material'),
        ),
    ]
