# Generated by Django 5.2 on 2026-04-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_plugin', '0002_alter_product_quantity_in_stock_productmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
