# Generated by Django 5.2 on 2026-04-26 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mrp_production_plugin', '0001_initial'),
        ('orders_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders_plugin.order'),
        ),
    ]
