# Generated by Django 5.2 on 2026-04-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_production_plugin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_stock', 'In-Stock'), ('urgent', 'Urgent')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='production',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Low'), ('urgent', 'Urgent'), ('out_of_stock', 'Out-of-stock')], default='low', max_length=20),
        ),
    ]
