# Generated by Django 5.2 on 2026-04-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_production_plugin', '0003_production_delivery_status_production_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='production',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='low', max_length=20),
        ),
    ]
