# Generated by Django 5.2 on 2026-04-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_production_plugin', '0004_alter_production_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20),
        ),
    ]
