# Generated by Django 5.2 on 2026-04-28 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_production_plugin', '0005_alter_production_priority_level'),
        ('orders_plugin', '0005_order_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='order',
        ),
        migrations.AddField(
            model_name='production',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='production', to='orders_plugin.orderitem'),
            preserve_default=False,
        ),
    ]
