# Generated by Django 5.2 on 2026-04-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_production_plugin', '0006_remove_production_order_production_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
